# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"\x81\x01\n\x10\x44\x65tectionRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12#\n\x04user\x18\x02 \x01(\x0b\x32\x15.fraud_detection.User\x12\x37\n\x0e\x62illingAddress\x18\x03 \x01(\x0b\x32\x1f.fraud_detection.BillingAddress\"6\n\x11\x44\x65tectionResponse\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65tected\x18\x02 \x01(\x08\".\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2d\n\x0e\x46raudDetection\x12R\n\tDetection\x12!.fraud_detection.DetectionRequest\x1a\".fraud_detection.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=42
  _globals['_USER']._serialized_end=79
  _globals['_BILLINGADDRESS']._serialized_start=81
  _globals['_BILLINGADDRESS']._serialized_end=172
  _globals['_DETECTIONREQUEST']._serialized_start=175
  _globals['_DETECTIONREQUEST']._serialized_end=304
  _globals['_DETECTIONRESPONSE']._serialized_start=306
  _globals['_DETECTIONRESPONSE']._serialized_end=360
  _globals['_ERRORRESPONSE']._serialized_start=362
  _globals['_ERRORRESPONSE']._serialized_end=408
  _globals['_FRAUDDETECTION']._serialized_start=410
  _globals['_FRAUDDETECTION']._serialized_end=510
# @@protoc_insertion_point(module_scope)
