# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x0bsuggestions\"\"\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\"\n\x0fPrepareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"*\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd2\x01\n\rBooksDatabase\x12;\n\x04Read\x12\x18.suggestions.ReadRequest\x1a\x19.suggestions.ReadResponse\x12>\n\x05Write\x12\x19.suggestions.WriteRequest\x1a\x1a.suggestions.WriteResponse\x12\x44\n\x07Prepare\x12\x1b.suggestions.PrepareRequest\x1a\x1c.suggestions.PrepareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREREQUEST']._serialized_start=31
  _globals['_PREPAREREQUEST']._serialized_end=65
  _globals['_PREPARERESPONSE']._serialized_start=67
  _globals['_PREPARERESPONSE']._serialized_end=101
  _globals['_READREQUEST']._serialized_start=103
  _globals['_READREQUEST']._serialized_end=129
  _globals['_READRESPONSE']._serialized_start=131
  _globals['_READRESPONSE']._serialized_end=160
  _globals['_WRITEREQUEST']._serialized_start=162
  _globals['_WRITEREQUEST']._serialized_end=204
  _globals['_WRITERESPONSE']._serialized_start=206
  _globals['_WRITERESPONSE']._serialized_end=238
  _globals['_BOOKSDATABASE']._serialized_start=241
  _globals['_BOOKSDATABASE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
