# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x0bsuggestions\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"*\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x90\x01\n\rBooksDatabase\x12=\n\x04Read\x12\x18.suggestions.ReadRequest\x1a\x19.suggestions.ReadResponse\"\x00\x12@\n\x05Write\x12\x19.suggestions.WriteRequest\x1a\x1a.suggestions.WriteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=31
  _globals['_READREQUEST']._serialized_end=57
  _globals['_READRESPONSE']._serialized_start=59
  _globals['_READRESPONSE']._serialized_end=88
  _globals['_WRITEREQUEST']._serialized_start=90
  _globals['_WRITEREQUEST']._serialized_end=132
  _globals['_WRITERESPONSE']._serialized_start=134
  _globals['_WRITERESPONSE']._serialized_end=166
  _globals['_BOOKSDATABASE']._serialized_start=169
  _globals['_BOOKSDATABASE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
