# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"L\n\x13\x45xecuteOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.order_executor.Item\"8\n\x14\x45xecuteOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2l\n\rOrderExecutor\x12[\n\x0c\x45xecuteOrder\x12#.order_executor.ExecuteOrderRequest\x1a$.order_executor.ExecuteOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=40
  _globals['_ITEM']._serialized_end=78
  _globals['_EXECUTEORDERREQUEST']._serialized_start=80
  _globals['_EXECUTEORDERREQUEST']._serialized_end=156
  _globals['_EXECUTEORDERRESPONSE']._serialized_start=158
  _globals['_EXECUTEORDERRESPONSE']._serialized_end=214
  _globals['_ORDEREXECUTOR']._serialized_start=216
  _globals['_ORDEREXECUTOR']._serialized_end=324
# @@protoc_insertion_point(module_scope)
