# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from order_executor import order_executor_pb2 as order__executor_dot_order__executor__pb2


class OrderExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendElectionMessage = channel.unary_unary(
                '/order_executor.OrderExecutor/SendElectionMessage',
                request_serializer=order__executor_dot_order__executor__pb2.ElectionMessageRequest.SerializeToString,
                response_deserializer=order__executor_dot_order__executor__pb2.ElectionMessageResponse.FromString,
                )
        self.ReceiveElectionMessage = channel.unary_unary(
                '/order_executor.OrderExecutor/ReceiveElectionMessage',
                request_serializer=order__executor_dot_order__executor__pb2.ElectionMessageRequest.SerializeToString,
                response_deserializer=order__executor_dot_order__executor__pb2.ElectionMessageResponse.FromString,
                )
        self.DequeueOrder = channel.unary_unary(
                '/order_executor.OrderExecutor/DequeueOrder',
                request_serializer=order__executor_dot_order__executor__pb2.DequeueOrderRequest.SerializeToString,
                response_deserializer=order__executor_dot_order__executor__pb2.DequeueOrderResponse.FromString,
                )


class OrderExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendElectionMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveElectionMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendElectionMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendElectionMessage,
                    request_deserializer=order__executor_dot_order__executor__pb2.ElectionMessageRequest.FromString,
                    response_serializer=order__executor_dot_order__executor__pb2.ElectionMessageResponse.SerializeToString,
            ),
            'ReceiveElectionMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveElectionMessage,
                    request_deserializer=order__executor_dot_order__executor__pb2.ElectionMessageRequest.FromString,
                    response_serializer=order__executor_dot_order__executor__pb2.ElectionMessageResponse.SerializeToString,
            ),
            'DequeueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueOrder,
                    request_deserializer=order__executor_dot_order__executor__pb2.DequeueOrderRequest.FromString,
                    response_serializer=order__executor_dot_order__executor__pb2.DequeueOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_executor.OrderExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendElectionMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/SendElectionMessage',
            order__executor_dot_order__executor__pb2.ElectionMessageRequest.SerializeToString,
            order__executor_dot_order__executor__pb2.ElectionMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveElectionMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/ReceiveElectionMessage',
            order__executor_dot_order__executor__pb2.ElectionMessageRequest.SerializeToString,
            order__executor_dot_order__executor__pb2.ElectionMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DequeueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/DequeueOrder',
            order__executor_dot_order__executor__pb2.DequeueOrderRequest.SerializeToString,
            order__executor_dot_order__executor__pb2.DequeueOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
