# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\"\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\"\n\x0fPrepareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"3\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x92\x01\n\rPaymentSystem\x12\x43\n\x0e\x45xecutePayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12<\n\x07Prepare\x12\x17.payment.PrepareRequest\x1a\x18.payment.PrepareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREREQUEST']._serialized_start=26
  _globals['_PREPAREREQUEST']._serialized_end=60
  _globals['_PREPARERESPONSE']._serialized_start=62
  _globals['_PREPARERESPONSE']._serialized_end=96
  _globals['_PAYMENTREQUEST']._serialized_start=98
  _globals['_PAYMENTREQUEST']._serialized_end=148
  _globals['_PAYMENTRESPONSE']._serialized_start=150
  _globals['_PAYMENTRESPONSE']._serialized_end=201
  _globals['_PAYMENTSYSTEM']._serialized_start=204
  _globals['_PAYMENTSYSTEM']._serialized_end=350
# @@protoc_insertion_point(module_scope)
